server:
   error:
      include-stacktrace : on_trace_param

spring:
   datasource:
      url: jdbc:mysql://localhost:3307/anime?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=America/Halifax
      username: user
      password: 123
   jpa:
      hibernate:
         ddl-auto: update
#      properties:
#        hibernate: 
#         format_sql: false
#      show-sql: true

logging:
  level:
    org:
      hibernate:
        SQL: debug  
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

springdoc:
  swagger-ui:
    path: /swagger-ui.html  
  api-docs:
    path: /api-docs
 
management:
  endpoints:
    web:
      exposure:
        include: info, health, metrics, prometheus
  endpoint:
    health:
      show-details: when_authorized

info:
  app: Spring Boot 2 Fundamentals - RLSP
  linkined: https://www.linkedin.com/in/rodrigo-ls-pires/
  github: https://github.com/rlatorraca/SprinBoot2-Fundamentals