server:
   error:
      include-stacktrace : on_trace_param

spring:
   datasource:
      url: jdbc:mysql://localhost:3307/anime?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=America/Halifax
      username: user
      password: 123
   jpa:
      hibernate:
         ddl-auto: update